### ISSUE TITLE
Improve Build Process

### ISSUE THREAD

**Issue by sbernard31** [eclipse-leshan/leshan#1477]
Some days ago we face several issue with [jenkins instance](https://ci.eclipse.org/leshan/). 
(See for more details : https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3429)

This lead to several possible improvement : 
 - [x] (short term) avoid agressive polling to trigger build.  (https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3435#note_1184473)
 - [x]  ~[use webhooks to trigger build](https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3435) which [seems more flexible to use with jenkins pipeline](https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3435#note_1185097).~ include in :point_down: 
 - [x] https://github.com/eclipse-leshan/leshan/pull/1487 for `master`
 - [x]  https://github.com/eclipse-leshan/leshan/pull/1493
 - [x] https://github.com/eclipse-leshan/leshan/pull/1484
 - [x] Update README  and sandbox to use new artifacts URL.

While we are playing with build system, it's probably also time to consider to : 
- [x] https://github.com/eclipse-leshan/leshan/issues/1412
- [x] Removing build-number warning : https://github.com/mojohaus/buildnumber-maven-plugin/issues/199
- [x] https://github.com/eclipse-leshan/leshan/pull/1491. (mainly about ` Parameter 'localRepository' is deprecated`)
- [x] https://github.com/eclipse-leshan/leshan/pull/1496

**Comment by sbernard31** [comment]
@msangoi, @jvermillard, @JaroslawLegierski  if you have experience with **jenkins pipeline** and you think it's not so good, it's  still time to stop the machine.

**Comment by sbernard31** [comment]
> Those days I mainly use GitHub Actions so I have no opinions on Jenkins pipelines

Ok Thx for feedback. Just to let you know we also use github actions to validate PR but I don't think it's possible to use it to release eclipse project :thinking:.
My current feeling about github action I don't like it so much...  I'm not sure I like jenkins too :sweat_smile:

**Comment by sbernard31** [comment]
>  Removing build-number warning 
Can be achieve by forcing checkout in multibranch pipeline using `Check out to specific local branch` under additional behaviors within your branch source configuration.

**Comment by sbernard31** [comment]
I think we're done now.
